// SPDX-License-Identifier: GPL-3.0-only
// Build + run the conformance probe headlessly, then write docs/CONFORMANCE.md.
// The render-state / texture-op / format tables are probed empirically (coverage
// counters); the feature table is curated and paired with the verifying smoke.
import { execFileSync } from 'node:child_process';
import { createServer } from 'node:http';
import { statSync, writeFileSync, createReadStream } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';

const here = dirname(fileURLToPath(import.meta.url));
const repo = join(here, '..');
const buildDir = join(repo, 'build', 'emscripten');
const MIME = { '.js': 'text/javascript', '.wasm': 'application/wasm', '.html': 'text/html' };

execFileSync('bash', [join(repo, 'scripts', 'build-wasm.sh')], { stdio: 'inherit' });

writeFileSync(join(buildDir, 'conformance.html'),
  `<!doctype html><canvas id=canvas width=4 height=4></canvas>` +
  `<script>var Module={canvas:document.getElementById('canvas')};</script>` +
  `<script src="conformance.js"></script>`);

const server = createServer((req, res) => {
  const p = decodeURIComponent(req.url.split('?')[0]);
  const file = join(buildDir, p === '/' ? 'conformance.html' : p);
  let st; try { st = statSync(file); } catch { res.writeHead(404).end(); return; }
  res.writeHead(200, { 'Content-Type': MIME[file.slice(file.lastIndexOf('.'))] || 'application/octet-stream',
    'Content-Length': st.size });
  createReadStream(file).pipe(res);
});
await new Promise((r) => server.listen(0, '127.0.0.1', r));
const base = `http://127.0.0.1:${server.address().port}`;

const require = createRequire(join(repo, 'web-runtime', 'package.json'));
const { chromium } = require('playwright');
const args = ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader'];
let browser;
for (const opts of [{ channel: 'chrome' }, { executablePath: '/usr/bin/google-chrome' }, {}]) {
  try { browser = await chromium.launch({ headless: true, args, ...opts }); break; } catch { /* next */ }
}
const page = await browser.newPage();
await page.goto(`${base}/conformance.html`);
const probed = await page.waitForFunction(() => window.__conf, null, { timeout: 30000 }).then((h) => h.jsonValue());
await browser.close(); server.close();
const data = JSON.parse(probed);
if (data.error) throw new Error(data.error);

// Curated feature coverage (paired with the smoke that verifies it).
const features = [
  ['Device / present', 'Direct3DCreate8, CreateDevice, Clear, Present', 'yes', 'd3d8_smoke'],
  ['Vertex/index buffers', 'CreateVertexBuffer/IndexBuffer, Lock/Unlock, SetStreamSource, SetIndices', 'yes', 'draw_smoke'],
  ['FVF: XYZ / NORMAL / DIFFUSE / TEX1', 'attribute layout in FVF order', 'yes', 'draw_smoke / light_smoke'],
  ['FVF: XYZRHW (pre-transformed)', 'screen-space UI/HUD vertices (rhw=1)', 'yes', 'rhw_smoke'],
  ['FVF: SPECULAR, multi-texcoord', 'extra colour / texcoord sets', 'no', '—'],
  ['DrawIndexedPrimitive (TRIANGLELIST)', 'other primitive types not yet wired', 'partial', 'draw_smoke'],
  ['Transforms: WORLD / VIEW / PROJECTION', 'row-major uploaded transposed', 'yes', 'draw_smoke'],
  ['Textures: A8R8G8B8 + LockRect', 'level 0, nearest, clamp', 'yes', 'draw_tex_smoke'],
  ['Texture combiners: MODULATE, SELECTARG1', 'stage-0 color op', 'yes', 'draw_tex_smoke'],
  ['Render states: depth / blend / cull / alpha-test', 'the common subset', 'yes', 'render_state_smoke'],
  ['Lighting: directional / point / spot', 'all three D3DLIGHT types', 'yes', 'light/point/spot_light_smoke'],
  ['Lighting: ambient + diffuse + specular', 'full FF equation (infinite viewer)', 'yes', 'light/specular_smoke'],
  ['Lighting: local viewer, >8 lights', 'infinite viewer only; 8-light cap', 'no', '—'],
  ['Fog: linear', 'eye-space depth blend', 'yes', 'fog_smoke'],
  ['Fog: EXP / EXP2', 'flagged via coverage', 'no', '—'],
  ['Coverage / fallback layer', 'dx8wasm_get_coverage + unhandled callback', 'yes', 'coverage_smoke'],
];

const mark = (h) => (h ? '✅ handled' : '⚠️ fallback');
const featMark = { yes: '✅', partial: '🟡', no: '❌' };
const rows = (arr) => arr.map((e) => `| \`${e.name}\` | ${mark(e.handled)} |`).join('\n');
const count = (arr) => `${arr.filter((e) => e.handled).length}/${arr.length}`;

const md = `# Conformance matrix

Generated by \`node scripts/conformance.mjs\`. The three token tables below are
**probed empirically** — the conformance program sets each token on a live
device and reads the coverage counters to decide handled vs fallback, so this
report can't drift from what the runtime actually does. The feature table is
curated and paired with the pixel smoke that verifies it.

Scope: the fixed-function subset a DirectX-8 game (target: C&C Generals) needs.
"fallback" means the token is safely ignored/substituted and logged via the
coverage layer — never silently wrong.

## Render states (${count(data.renderStates)} handled)

| State | Status |
|-------|--------|
${rows(data.renderStates)}

## Texture-stage color ops (${count(data.textureOps)} handled)

| Op | Status |
|----|--------|
${rows(data.textureOps)}

## Texture formats (${count(data.formats)} handled)

| Format | Status |
|--------|--------|
${rows(data.formats)}

## Feature coverage

| Feature | Notes | Status | Verified by |
|---------|-------|--------|-------------|
${features.map(([f, n, s, t]) => `| ${f} | ${n} | ${featMark[s]} ${s} | ${t} |`).join('\n')}
`;

writeFileSync(join(repo, 'docs', 'CONFORMANCE.md'), md);
console.log(`wrote docs/CONFORMANCE.md — render states ${count(data.renderStates)}, ` +
  `ops ${count(data.textureOps)}, formats ${count(data.formats)}`);
