#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-only
# Concatenate the core AI-consumable docs into a single llms-full.txt, for tools
# that prefer one file over the linked llms.txt index. Regenerate after doc edits.
set -euo pipefail
cd "$(dirname "$0")/.."

DOCS=(
  AGENTS.md
  docs/SDK_REFERENCE.md
  docs/INTEGRATION.md
  docs/ARCHITECTURE.md
  docs/COMPATLIB.md
  docs/CONFORMANCE.md
)

out=llms-full.txt
{
  echo "# dx8wasm — full LLM context"
  echo
  echo "Concatenation of the core docs (generated by scripts/gen-llms-full.sh)."
  echo "Canonical sources live in the repo; regenerate after edits."
  for f in "${DOCS[@]}"; do
    echo
    echo "================================================================"
    echo "# FILE: $f"
    echo "================================================================"
    echo
    cat "$f"
  done
} > "$out"

echo "wrote $out ($(wc -l < "$out") lines from ${#DOCS[@]} docs)"
